administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
    #para excel
    path('exportar_excel/', views.exportar_excel, name='exportar_excel'),
    path('exportar_excel_perfiles/', views.exportar_excel_perfiles, name='exportar_excel_perfiles'),
    
    
    path('aprobar_actividad/<int:actividad_id>/', views.aprobar_actividad, name='aprobar_actividad'),
    path('habilitar_perfiles/', views.listar_tribunales_perfiles, name='listar_tribunales_perfiles'),
    path('habilitar_perfiles/agregar/', views.agregar_tribunales_perfil, name='agregar_tribunales_perfil'),
    path('habilitar_perfiles/editar/<int:pk>/', views.editar_tribunales_perfil, name='editar_tribunales_perfil'),
    path('filtrartribunales/', views.filtrartribunales, name='filtrartribunales'),
    path('filtraracta/', views.filtraracta, name='filtraracta'), 
    
    path('agregar_viadiplomado/', views.agregar_viadiplomado, name='agregar_viadiplomado'),
    path('proyectofinal/acta_viadiplomado_list', views.actaviadiplomado_list, name='actaviadiplomado_list'),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) filtrartribunales
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  
import inflect 
from num2words import num2words

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
    ('Proceso', 'Proceso'),
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class Estudiante(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    Ru = models.CharField(max_length=20, null=True, blank=True)
    
class Docente(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    especialidad = models.CharField(max_length=100)
    titulo = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.user.nombre}'

class Facultad(models.Model):
    nombre = models.CharField(max_length=150, unique=True)
    
    def __str__(self):
        return self.nombre


# Modelo de Carreras
class Carrera(models.Model):
    nombre_carrera = models.CharField(max_length=150)
    facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_carrera

# Modelo de Semestre
class Semestre(models.Model):
    S_Semestre=models.CharField(max_length=100,verbose_name='Semestre')
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.S_Semestre

# Modelo de Materia
class Materia(models.Model):
    nombre_materia = models.CharField(max_length=150)
    codigo = models.CharField(max_length=50, unique=True)
    semestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_materia

# Modelo de Gestión
class Gestion(models.Model):
    anio = models.IntegerField(unique=True)
    
    def __str__(self):
         return str(self.anio)

# Modelo de Periodos
class Periodo(models.Model):
    numero = models.IntegerField()
    gestion = models.ForeignKey(Gestion, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-numero','-gestion__anio']  
    
    def __str__(self):
        return f'{self.numero}/{self.gestion.anio}'  


class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Título')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripción Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='perfil_name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='perfil_name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='perfil_name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripción', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentación', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario


class HabilitarTribunalesPerfil(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='habilitar_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='habilitar_user_uno')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Acta')
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_tutor', on_delete=models.CASCADE, verbose_name='Tutor')
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_1', on_delete=models.CASCADE, verbose_name='Jurado 1')
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_2', on_delete=models.CASCADE, verbose_name='Jurado 2')
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_3', on_delete=models.CASCADE, verbose_name='Jurado 3')
    
    class Meta:
        verbose_name_plural = "Habilitar Tribunales Perfil"
        verbose_name = "Habilitar Tribunal Perfil"
    
    def __str__(self):
        return self.pertitulo

class ActaProyectoPerfil(models.Model):
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE )
    perperiodo = models.ForeignKey(Periodo, on_delete=models.CASCADE, null=True)
    acta = models.CharField(max_length=30, unique=True )
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    estudiante_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='acta_estudianteuno')
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)

seg_mod_graduacion/templates/perfil/agregar_tribunales_perfil.html
{% extends 'dashboard.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container px-lg-5 fontI colortext">
  <div class="pb-5 no-gutters p-lg-5 p-2">
    <div class="no-gutte p-lg-4 p-0">
      <h1 class="px-lg-5 title px-3 colortext py-5 fontI">
        Habilitación de Tribunales y Tutor para Defensa de Perfil
        <svg xmlns="http://www.w3.org/2000/svg" width="76" height="76" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
          <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
          <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
        </svg>
      </h1>
      <div class="card-body font px-lg-5 px-3">
        <form method="post" id="approvalForm" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="fechas">
            <div class="row mb-3">
              <div class="col-md-12 pt-1">
                {{ form.user.label_tag }} <br>{{ form.user }}
              </div>
            </div><br>
            <div class="row mb-3">
              <div class="col-md-6 pt-1">
                {{ form.user_uno.label_tag }} <br>{{ form.user_uno }}
              </div>
              <div class="col-md-6 pt-1">
                {{ form.tutor.label_tag }} <br>{{ form.tutor }}
              </div>
              <div class="col-md-12 pt-1">
                {{ form.pertitulo.label_tag }}<br> {{ form.pertitulo }}
              </div>
              <div class="col-md-6 pt-1">
                {{ form.permodalidad.label_tag }}<br> {{ form.permodalidad }}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.jurado_1.label_tag }}<br> {{ form.jurado_1 }}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_2.label_tag }}<br> {{ form.jurado_2 }}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_3.label_tag }}<br> {{ form.jurado_3 }}
              </div>
            </div>
            <br>
            <button type="button" class="btn btn-primary fontII" data-bs-toggle="modal" data-bs-target="#approveModal">Confirmar Activación</button>
            <a class="btn btn-danger fontII" href="{% url 'listar_tribunales_perfiles' %}">Cancelar</a>
          </div>
        </form>
        <br>
      </div>
    </div>
  </div>
</div><br>
<div class="modal fade" id="approveModal" tabindex="-1" aria-labelledby="approveModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="approveModalLabel">Confirmar Aprobación</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¿Estás seguro que quiere habilitar tribunal y tutor a este usuario?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark fontII" onclick="submitForm('aprobar')">Sí, Aprobar</button>
      </div>
    </div>
  </div>
</div>

{% block scripts %}
  
<script>
    $(document).ready(function() {
        // Detecta cambios en el campo 'user'
        $('#id_user').change(function() {
            const userId = $(this).val();  // Obtiene el ID del usuario seleccionado
    
            if (userId) {
                // Si hay un usuario seleccionado, se hace la solicitud AJAX
                $.ajax({
                    url: '{% url "filtrartribunales" %}',  // URL donde se manejará la solicitud en Django
                    data: {
                        'user_id': userId  // Pasa el ID del usuario seleccionado
                    },
                    success: function(response) {
                        // Rellena los campos con los datos obtenidos
                        $('#id_user_uno').val(response.user_uno); 
                        $('#id_pertitulo').val(response.pertitulo); 
                        $('#id_permodalidad').val(response.permodalidad); 
                    }
                });
            } else {
                // Si no hay un usuario seleccionado, limpiar los campos
                $('#id_user_uno').val(''); 
                $('#id_pertitulo').val(''); 
                $('#id_permodalidad').val(''); 
            }
        });
    });
    
  function submitForm(action) {
    const form = document.getElementById('approvalForm');
    const hiddenInput = document.createElement('input');
    hiddenInput.type = 'hidden';
    hiddenInput.name = action;
    hiddenInput.value = 'true'; // Agrega un valor al input oculto
    form.appendChild(hiddenInput);
    form.submit();
  } 
</script>
{% endblock %}
{% endblock %}

seg_mod_graduacion/templates/perfil/editar_tribunales_perfil.html
{% extends 'dashboard.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container px-lg-5 fontI colortext">
  <div class="pb-5 no-gutters p-lg-5 p-2">
    <div class="no-gutte p-lg-4 p-0">
      <h1 class="px-lg-5 title px-3 colortext py-5 fontI">
        Habilitación de Tribunales y Tutor para Defensa de Perfil
        <svg xmlns="http://www.w3.org/2000/svg" width="76" height="76" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
          <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
          <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
        </svg>
      </h1>
      <div class="card-body font px-lg-5 px-3">
        <form method="post" id="approvalForm" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="fechas">
            <div class="row mb-3">
                <div class="col-md-12 pt-1">
                    {{ form.user.label_tag }} <br>{{ form.user }}
                    <input type="hidden" name="user" value="{{ form.user.value }}">
                </div>
            </div><br>
            <div class="row mb-3">
                <div class="col-md-6 pt-1">
                    {{ form.user_uno.label_tag }} <br>{{ form.user_uno }}
                    <input type="hidden" name="user_uno" value="{{ form.user_uno.value }}">
                </div>
                <div class="col-md-6 pt-1">
                    {{ form.tutor.label_tag }} <br>{{ form.tutor }}
                </div>
            </div>
            <div class="col-md-12 pt-1">
                {{ form.pertitulo.label_tag }}<br> {{ form.pertitulo }}
            </div>
            <div class="col-md-6 pt-1">
                {{ form.permodalidad.label_tag }}<br> {{ form.permodalidad }}
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.jurado_1.label_tag }}<br> {{ form.jurado_1 }}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_2.label_tag }}<br> {{ form.jurado_2 }}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_3.label_tag }}<br> {{ form.jurado_3 }}
              </div>
            </div>
            <br>
            <button type="button" class="btn btn-primary fontII" data-bs-toggle="modal" data-bs-target="#approveModal">Confirmar Activación</button>
            <a class="btn btn-danger fontII" href="{% url 'listar_tribunales_perfiles' %}">Cancelar</a>
          </div>
        </form>
        <br>
      </div>
    </div>
  </div>
</div><br>
<div class="modal fade" id="approveModal" tabindex="-1" aria-labelledby="approveModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="approveModalLabel">Confirmar Aprobación</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¿Estás seguro que quiere habilitar tribunal y tutor a este usuario?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark fontII" onclick="submitForm('aprobar')">Sí, Aprobar</button>
      </div>
    </div>
  </div>
</div>

{% block scripts %}
  
<script>
    $(document).ready(function() {
        // Detecta cambios en el campo 'user'
        $('#id_user').change(function() {
            const userId = $(this).val();  // Obtiene el ID del usuario seleccionado
    
            if (userId) {
                // Si hay un usuario seleccionado, se hace la solicitud AJAX
                $.ajax({
                    url: '{% url "filtrartribunales" %}',  // URL donde se manejará la solicitud en Django
                    data: {
                        'user_id': userId  // Pasa el ID del usuario seleccionado
                    },
                    success: function(response) {
                        // Rellena los campos con los datos obtenidos
                        $('#id_user_uno').val(response.user_uno); 
                        $('#id_pertitulo').val(response.pertitulo); 
                        $('#id_permodalidad').val(response.permodalidad); 
                    }
                });
            } else {
                // Si no hay un usuario seleccionado, limpiar los campos
                $('#id_user_uno').val(''); 
                $('#id_pertitulo').val(''); 
                $('#id_permodalidad').val(''); 
            }
        });
    });
    
  function submitForm(action) {
    const form = document.getElementById('approvalForm');
    const hiddenInput = document.createElement('input');
    hiddenInput.type = 'hidden';
    hiddenInput.name = action;
    hiddenInput.value = 'true'; // Agrega un valor al input oculto
    form.appendChild(hiddenInput);
    form.submit();
  } 
</script>
{% endblock %}
{% endblock %}