administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
    #para excel
    path('exportar_excel/', views.exportar_excel, name='exportar_excel'),
    path('exportar_excel_perfiles/', views.exportar_excel_perfiles, name='exportar_excel_perfiles'),
    
    
    path('aprobar_actividad/<int:actividad_id>/', views.aprobar_actividad, name='aprobar_actividad'),
    path('habilitar_perfiles/', views.listar_tribunales_perfiles, name='listar_tribunales_perfiles'),
    path('habilitar_perfiles/agregar/', views.agregar_tribunales_perfil, name='agregar_tribunales_perfil'),
    path('habilitar_perfiles/editar/<int:pk>/', views.editar_tribunales_perfil, name='editar_tribunales_perfil'),
    path('filtrartribunales/', views.filtrartribunales, name='filtrartribunales'),
    path('filtraracta/', views.filtraracta, name='filtraracta'), 
    
    path('agregar_viadiplomado/', views.agregar_viadiplomado, name='agregar_viadiplomado'),
    path('proyectofinal/acta_viadiplomado_list', views.actaviadiplomado_list, name='actaviadiplomado_list'),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) filtrartribunales
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  
import inflect 
from num2words import num2words

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
    ('Proceso', 'Proceso'),
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class Estudiante(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    Ru = models.CharField(max_length=20, null=True, blank=True)
    
class Docente(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    especialidad = models.CharField(max_length=100)
    titulo = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.user.nombre}'

class Facultad(models.Model):
    nombre = models.CharField(max_length=150, unique=True)
    
    def __str__(self):
        return self.nombre


# Modelo de Carreras
class Carrera(models.Model):
    nombre_carrera = models.CharField(max_length=150)
    facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_carrera

# Modelo de Semestre
class Semestre(models.Model):
    S_Semestre=models.CharField(max_length=100,verbose_name='Semestre')
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.S_Semestre

# Modelo de Materia
class Materia(models.Model):
    nombre_materia = models.CharField(max_length=150)
    codigo = models.CharField(max_length=50, unique=True)
    semestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_materia

# Modelo de Gestión
class Gestion(models.Model):
    anio = models.IntegerField(unique=True)
    
    def __str__(self):
         return str(self.anio)

# Modelo de Periodos
class Periodo(models.Model):
    numero = models.IntegerField()
    gestion = models.ForeignKey(Gestion, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-numero','-gestion__anio']  
    
    def __str__(self):
        return f'{self.numero}/{self.gestion.anio}'  


class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Título')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripción Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='perfil_name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='perfil_name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='perfil_name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripción', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentación', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario


class HabilitarTribunalesPerfil(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='habilitar_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='habilitar_user_uno')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Acta')
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_tutor', on_delete=models.CASCADE, verbose_name='Tutor')
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_1', on_delete=models.CASCADE, verbose_name='Jurado 1')
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_2', on_delete=models.CASCADE, verbose_name='Jurado 2')
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_3', on_delete=models.CASCADE, verbose_name='Jurado 3')
    
    class Meta:
        verbose_name_plural = "Habilitar Tribunales Perfil"
        verbose_name = "Habilitar Tribunal Perfil"
    
    def __str__(self):
        return self.pertitulo

class ActaProyectoPerfil(models.Model):
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE )
    perperiodo = models.ForeignKey(Periodo, on_delete=models.CASCADE, null=True)
    acta = models.CharField(max_length=30, unique=True )
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    estudiante_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='acta_estudianteuno')
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)

seg_mod_graduacion/templates/actas/agregar_actaperfil.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container no-gutters p-lg-5 p-3 font ">
  <div class="no-gutte container p-lg-5 p-0">
    <h1 class="text-center colortitle pb-2 titlesuperior">REGISTRO DE ACTA DEFENSA DE PERFIL DE PROYECTO</h1>
    {% if form_disabled %}
      <p class="text-end text colorestados ">El formulario de investigación está deshabilitado para el Usuario.</p>
    {% endif %}
    
    <article class="pb-2 colortext" >
      <form id="pot" method="post" enctype="multipart/form-data" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        <div class="fechas fontI">
            <div class="row mb-3">
              <div class="col-md-8 pt-1">
                {{ form.estudiante.label_tag }}<br>{{ form.estudiante }}
                {% if form.estudiante.errors %}
                  <div class="text-danger">{{ form.estudiante.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.carrera.label_tag }}<br>{{ form.carrera }}
                {% if form.carrera.errors %}
                  <div class="text-danger">{{ form.carrera.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.lugar.label_tag }}<br>{{ form.lugar }}
                {% if form.lugar.errors %}
                  <div class="text-danger">{{ form.lugar.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.acta.label_tag }}<br>{{ form.acta }}
                {% if form.acta.errors %}
                  <div class="text-danger">{{ form.acta.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.perperiodo.label_tag }}<br>
                <select name="perperiodo" class="form-control">
                    {% for periodo in ultimos_periodos %}
                        <option value="{{ periodo.id }}">{{ periodo }}</option>
                    {% endfor %}
                </select>
                {% if form.perperiodo.errors %}
                    <div class="text-danger">{{ form.perperiodo.errors }}</div>
                {% endif %}
              </div>
            
              
            </div>
            <div class="row mb-3">
              <div class="col-md-6 pt-1">
                {{ form.estudiante_uno.label_tag }}<br>{{ form.estudiante_uno }}
                {% if form.estudiante_uno.errors %}
                  <div class="text-danger">{{ form.estudiante_uno.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-6 pt-1">
                {{ form.tutor.label_tag }}<br>{{ form.tutor }}
                {% if form.tutor.errors %}
                  <div class="text-danger">{{ form.tutor.errors }}</div>
                {% endif %}
              </div>
              
            </div>
            <div class="col-md-12 pt-1">
              {{ form.titulo.label_tag }}<br>{{ form.titulo }}
              {% if form.titulo.errors %}
                <div class="text-danger">{{ form.titulo.errors }}</div>
              {% endif %}
            </div>
            <div class="row mb-4 pt-2">
              <div class="col-md-4 pt-1">
                {{ form.fechadefensa.label_tag }}<br>{{ form.fechadefensa }}
                {% if form.fechadefensa.errors %}
                  <div class="text-danger">{{ form.fechadefensa.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.horainicio.label_tag }}<br>{{ form.horainicio }}
                {% if form.horainicio.errors %}
                    <div class="text-danger">{{ form.horainicio.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.horafin.label_tag }}<br>{{ form.horafin }}
                {% if form.horafin.errors %}
                    <div class="text-danger">{{ form.horafin.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.jurado_1.label_tag }}<br>{{ form.jurado_1 }}
                {% if form.jurado_1.errors %}
                  <div class="text-danger">{{ form.jurado_1.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_2.label_tag }}<br>{{ form.jurado_2 }}
                {% if form.jurado_2.errors %}
                  <div class="text-danger">{{ form.jurado_2.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_3.label_tag }}<br>{{ form.jurado_3 }}
                {% if form.jurado_3.errors %}
                  <div class="text-danger">{{ form.jurado_3.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6 pt-1">
                {{ form.modalidad.label_tag }}<br>{{ form.modalidad }}
                {% if form.modalidad.errors %}
                  <div class="text-danger">{{ form.modalidad.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-6 pt-1">
                {{ form.resultado.label_tag }}<br>{{ form.resultado }}
                {% if form.resultado.errors %}
                  <div class="text-danger">{{ form.resultado.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.observacion_1.label_tag }}<br>{{ form.observacion_1 }}
                {% if form.observacion_1.errors %}
                  <div class="text-danger">{{ form.observacion_1.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.observacion_2.label_tag }}<br>{{ form.observacion_2 }}
                {% if form.observacion_2.errors %}
                  <div class="text-danger">{{ form.observacion_2.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.observacion_3.label_tag }}<br>{{ form.observacion_3 }}
                {% if form.observacion_3.errors %}
                  <div class="text-danger">{{ form.observacion_3.errors }}</div>
                {% endif %}
              </div>
            </div>
          </div>
        <br>
        <input name="" id="" class="btn btn-dark me-2 fontII" type="submit" value="Enviar Información" {% if form_disabled %}disabled{% endif %}>
        <a class="btn btn-secondary fontII" href="{% url 'dashboard' %}">Cancelar</a>

      </form>
      {% block scripts %}
      
      <script>
        $(document).ready(function() {
          // Cuando el campo del estudiante cambia
          $('#id_estudiante').change(function() {
              var userId = $(this).val();  // Obtiene el ID del estudiante seleccionado
      
              // Verifica si se seleccionó un usuario válido
              if (userId) {
                  $.ajax({
                      url: '/filtraracta/',  // La URL a la que se hace la solicitud
                      data: {
                          'user_id': userId  // Parámetro que se envía al servidor
                      },
                      dataType: 'json',
                      success: function(data) {
                          if (data.error) {
                              alert(data.error);  // Muestra el error si lo hay
                          } else {
                              // Llenamos los campos del formulario con los datos obtenidos
                              $('#id_titulo').val(data.titulo);
                              $('#id_modalidad').val(data.modalidad);
                              $('#id_tutor').val(data.tutor);
                              $('#id_jurado_1').val(data.jurado_1);
                              $('#id_jurado_2').val(data.jurado_2);
                              $('#id_jurado_3').val(data.jurado_3);
                              $('#id_estudiante_uno').val(data.estudiante_uno);
                          }
                      },
                      error: function(xhr, status, error) {
                          console.error("Ocurrió un error: " + error);
                      }
                  });
              } else {
                  // Limpia los campos si no hay un estudiante seleccionado
                  $('#id_titulo').val('');
                  $('#id_modalidad').val('');
                  $('#id_tutor').val('');
                  $('#id_jurado_1').val('');
                  $('#id_jurado_2').val('');
                  $('#id_jurado_3').val('');
                  $('#id_estudiante_uno').val('');
                  alert("Por favor selecciona un estudiante válido.");
              }
          });
      });
      
        // Función para mostrar el modal de confirmación
        function showConfirmationModal(event) {
          event.preventDefault();
          $('#confirmationModal').modal('show'); 
          
          setTimeout(function() {
            $('#confirmationModal').modal('hide');
            document.getElementById("pot").submit(); 
          }, 2000);
        }

        document.addEventListener('DOMContentLoaded', function() {
          const estudianteSelects = [
            document.getElementById('id_estudiante'),
            document.getElementById('id_estudiante_uno'),
            document.getElementById('id_estudiante_dos')
          ];
          
          const juradoSelects = [
            document.getElementById('id_tutor'),
            document.getElementById('id_jurado_1'),
            document.getElementById('id_jurado_2'),
            document.getElementById('id_jurado_3')
          ];
        
          // Actualiza las opciones disponibles para los estudiantes
          function updateEstudianteOptions() {
            const selectedValues = estudianteSelects.map(select => select.value);
            estudianteSelects.forEach(select => {
              Array.from(select.options).forEach(option => {
                option.hidden = selectedValues.includes(option.value) && option.value !== select.value;
              });
            });
          }
        
          // Actualiza las opciones disponibles para los jurados
          function updateJuradoOptions() {
            const selectedValues = juradoSelects.map(select => select.value);
            juradoSelects.forEach(select => {
              Array.from(select.options).forEach(option => {
                option.hidden = selectedValues.includes(option.value) && option.value !== select.value;
              });
            });
          }
        
          // Agregar evento change para cada select de estudiantes
          estudianteSelects.forEach(select => {
            select.addEventListener('change', updateEstudianteOptions);
          });
        
          // Agregar evento change para cada select de jurados
          juradoSelects.forEach(select => {
            select.addEventListener('change', updateJuradoOptions);
          });
        
          // Ejecutar la función al cargar la página para ocultar opciones seleccionadas previamente
          updateEstudianteOptions();
          updateJuradoOptions();
        });

        
       
      </script>
            
      {% endblock %}
      
    </article>
  </div> 
</div><br>


<!-- Modal de confirmación -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmacion de Formulario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Exito!
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>



{% endblock %}