administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
    #para excel
    path('exportar_excel/', views.exportar_excel, name='exportar_excel'),
    path('exportar_excel_perfiles/', views.exportar_excel_perfiles, name='exportar_excel_perfiles'),
    
    
    path('aprobar_actividad/<int:actividad_id>/', views.aprobar_actividad, name='aprobar_actividad'),
    path('habilitar_perfiles/', views.listar_tribunales_perfiles, name='listar_tribunales_perfiles'),
    path('habilitar_perfiles/agregar/', views.agregar_tribunales_perfil, name='agregar_tribunales_perfil'),
    path('habilitar_perfiles/editar/<int:pk>/', views.editar_tribunales_perfil, name='editar_tribunales_perfil'),
    path('filtrartribunales/', views.filtrartribunales, name='filtrartribunales'),
    path('filtraracta/', views.filtraracta, name='filtraracta'), 
    
    path('agregar_viadiplomado/', views.agregar_viadiplomado, name='agregar_viadiplomado'),
    path('proyectofinal/acta_viadiplomado_list', views.actaviadiplomado_list, name='actaviadiplomado_list'),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) filtrartribunales
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  
import inflect 
from num2words import num2words

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
    ('Proceso', 'Proceso'),
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class Estudiante(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    Ru = models.CharField(max_length=20, null=True, blank=True)
    
class Docente(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    especialidad = models.CharField(max_length=100)
    titulo = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.user.nombre}'

class Facultad(models.Model):
    nombre = models.CharField(max_length=150, unique=True)
    
    def __str__(self):
        return self.nombre


# Modelo de Carreras
class Carrera(models.Model):
    nombre_carrera = models.CharField(max_length=150)
    facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_carrera

# Modelo de Semestre
class Semestre(models.Model):
    S_Semestre=models.CharField(max_length=100,verbose_name='Semestre')
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.S_Semestre

# Modelo de Materia
class Materia(models.Model):
    nombre_materia = models.CharField(max_length=150)
    codigo = models.CharField(max_length=50, unique=True)
    semestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_materia

# Modelo de Gestión
class Gestion(models.Model):
    anio = models.IntegerField(unique=True)
    
    def __str__(self):
         return str(self.anio)

# Modelo de Periodos
class Periodo(models.Model):
    numero = models.IntegerField()
    gestion = models.ForeignKey(Gestion, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-numero','-gestion__anio']  
    
    def __str__(self):
        return f'{self.numero}/{self.gestion.anio}'  


class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Título')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripción Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='perfil_name_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='perfil_name_useruno')
    user_dos = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Tercer participante', blank=True, null=True, related_name='perfil_name_userdos')
    habilitar_users = models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripción', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentación', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario


class HabilitarTribunalesPerfil(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado', related_name='habilitar_user')
    user_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='habilitar_user_uno')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Título Acta')
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_tutor', on_delete=models.CASCADE, verbose_name='Tutor')
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_1', on_delete=models.CASCADE, verbose_name='Jurado 1')
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_2', on_delete=models.CASCADE, verbose_name='Jurado 2')
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='habilitar_jurado_3', on_delete=models.CASCADE, verbose_name='Jurado 3')
    
    class Meta:
        verbose_name_plural = "Habilitar Tribunales Perfil"
        verbose_name = "Habilitar Tribunal Perfil"
    
    def __str__(self):
        return self.pertitulo

class ActaProyectoPerfil(models.Model):
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE )
    perperiodo = models.ForeignKey(Periodo, on_delete=models.CASCADE, null=True)
    acta = models.CharField(max_length=30, unique=True )
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    estudiante_uno = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Segundo participante', blank=True, null=True, related_name='acta_estudianteuno')
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)

seg_mod_graduacion/templates/invcientifica/agregar_investigacion.html
{% extends 'dashboard.html' %}

{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container p-lg-5 p-3 fontI no-gutters">
  <div class="no-gutte container p-lg-4 p-0 pb-2">
    <h1 class="text-center colortext py-2 titlesuperior">AGREGAR NUEVO FORMULARIO DE INVESTIGACIÓN CIENTÍFICA</h1>
    
    {% if form_disabled %}
      <p class="text-end text colorestados">El formulario de investigación está deshabilitado para el Usuario.</p>
    {% endif %}

    <article class="pb-3 colortext">
      <form id="pot" method="post" enctype="multipart/form-data" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        <div id="extra-users" style="display: block {% if form.habilitar_users.value %}block{% else %}none{% endif %};">
          <div class="row">
            <div class="col-md-12 col-11">
              {{ form.user_uno|as_crispy_field }}
            </div>
          </div>
        </div>
        <!-- Render the rest of the form excluding user_uno and user_dos -->
        {{ form.non_field_errors }}
        {% for field in form %}
          {% if field.name != 'user_uno' and field.name != 'user_dos' %}
            {{ field|as_crispy_field }}
          {% endif %}
        {% endfor %}
        <br>
        <!-- Submit and cancel buttons -->
        <input name="" id="" class="btn btn-primary me-2 fontII" type="submit" value="Enviar Información" {% if form_disabled %}disabled{% endif %}>
        <a class="btn btn-danger fontII" href="{% url 'dashboard' %}">Cancelar</a>
      </form>
      {% block scripts %}
      <script>
        $("#id_user_uno").select2();
        $("#id_user_dos").select2();

        const checkbox = document.getElementById('{{ form.habilitar_users.id_for_label }}');
        const extraUsersDiv = document.getElementById('extra-users');

        checkbox.addEventListener('change', function() {
          if (this.checked) {
            extraUsersDiv.style.display = 'block'; // Show the extra user fields
          } else {
            extraUsersDiv.style.display = 'none'; // Hide the extra user fields
          }
        });

        // Initialize visibility of extra user fields
        if (!checkbox.checked) {
          extraUsersDiv.style.display = 'none';
        }
      </script>
            
      {% endblock %}

    </article>
  </div>
</div><br>

<!-- Confirmation Modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmación de Formulario</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> <!-- Updated for Bootstrap 5 -->
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Éxito!
      </div>
    </div>
  </div>
</div>

<!-- Script to handle form submission and modal display -->
<script>
  function showConfirmationModal(event) {
    event.preventDefault(); 
    $('#confirmationModal').modal('show'); 
    
    setTimeout(function() {
      $('#confirmationModal').modal('hide'); 
      document.getElementById("pot").submit(); 
    }, 2000);  // Close the modal after 2 seconds and submit the form
  }
</script>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/global_settings.html
{% extends 'dashboard.html'%} {% load static %} {% load crispy_forms_tags %}{% block content %}
<h1 class="text-center font">HABILITACIÓN DE FECHAS PARA PROYECTO INTERACION SOCIAL</h1>
<div class="container mt-3 pt-3">
  <div class="row pb-5 ">
    <div class="col-md-8  offset-md-2 pb-5">
      <div class="card contdoc">
        <div class="card-body font text-center">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary fontII" type="submit">Guardar</button>
                <a class="btn btn-danger fontII" href="{% url 'dashboard' %}">Camcelar</a>
            </form>
        </div>
        <br />
      </div>
    </div>
  </div>
</div>
{% endblock %}